# Generated by Django 4.1 on 2022-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expiration', models.DateField()),
                ('storage', models.CharField(choices=[('R', 'Refrigerator'), ('L', 'Freezer')], default='R', max_length=1)),
                ('servings', models.IntegerField()),
            ],
        ),
    ]
